# Generated by Django 6.1.2 on 2026-10-07 18:27

import django.db.models.deletion
import games.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=games.models.make_code, max_length=8, unique=True)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('white_token', models.CharField(blank=True, max_length=40)),
                ('black_token', models.CharField(blank=True, max_length=40)),
                ('white_name', models.CharField(blank=True, max_length=150)),
                ('black_name', models.CharField(blank=True, max_length=150)),
                ('invited_token', models.CharField(blank=True, max_length=40)),
                ('initial_seconds', models.PositiveIntegerField(default=600)),
                ('increment_seconds', models.PositiveIntegerField(default=0)),
                ('white_ms', models.BigIntegerField(default=0)),
                ('black_ms', models.BigIntegerField(default=0)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('moves', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=8)),
                ('reason', models.CharField(blank=True, max_length=60)),
                ('draw_offer', models.CharField(blank=True, max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
