# Generated by Django 6.1.2 on 2026-10-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rematch_black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_white',
            field=models.BooleanField(default=False),
        ),
    ]
